name: Test SNILS generator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Build Alfred Workflow
        uses: mperezi/build-alfred-workflow@v1
        id: alfred_builder
        with:
          workflow_dir: src
          exclude_patterns: '*.pyc *__pycache__/*'

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: SNILS-generator-workflow
          path: ${{ steps.alfred_builder.outputs.workflow_file }}
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Test script
        run: node tests/run.js

